language: python
python:
    - 3.6
install:
    - pip install coverage
branches:
    only:
        - master
        - SDC-3960
addons:
    sonarcloud:
        organization: "kbrpurchase1"
script: 
    - coverage erase
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
